import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { BSD_RESIDENTIAL, ABSD, LTV, STRESS_TEST_RATE, TDSR_LIMIT, MSR_LIMIT, MORTGAGE_DUTY } from '../lib/calc/constants.js';

/**
 * The anti-drift suite.
 *
 * The rates have lived in two places — lib/calc/constants.js and the deck
 * research base — and they have been kept in step by someone remembering to.
 * These tests are what replaces the remembering. If a rate is changed in one
 * place and not the other, this suite goes red before anyone publishes a page
 * that contradicts the deck they are about to present from.
 *
 * It also enforces the publishing allowlist. The build pack contains the
 * commission rate card and the brand internals, and none of that may reach a
 * public page.
 */
const DIR = path.join(process.cwd(), 'content', 'guides');
const built = fs.existsSync(DIR) && fs.readdirSync(DIR).some(f => f.endsWith('.md'));
const has = built ? undefined : { skip: 'content/guides not built — run `npm run build:guides`' };

const read = slug => fs.readFileSync(path.join(DIR, `${slug}.md`), 'utf8');
const all = () => fs.readdirSync(DIR).filter(f => f.endsWith('.md')).map(f => [f, fs.readFileSync(path.join(DIR, f), 'utf8')]);
const pctIn = s => Number(String(s).replace(/[*\s%]/g, '')) / 100;
/* 0.55 * 100 is 55.00000000000001 in JavaScript, which builds a regex that
 * matches nothing and reports a rate conflict that does not exist. */
const asPct = n => String(Math.round(n * 1000) / 10);

/** One `####` section of a guide, so a regex cannot wander into the next table. */
function section(md, heading) {
  const i = md.indexOf(heading);
  assert.ok(i > -1, `no section headed ${heading}`);
  const rest = md.slice(i);
  const j = rest.slice(1).search(/\n#{2,6} /);
  return j > -1 ? rest.slice(0, j + 1) : rest;
}

/* ── the allowlist ──────────────────────────────────────────────────────── */

test('no guide publishes the commission, brand or build sections', has, () => {
  // Part C is the rate card, D is brand, E the deck outlines, F the build
  // prompt, G the open questions. None of it is for a reader.
  // The word "commission" is deliberately NOT forbidden. A seller's cost table
  // that omits the agent's fee understates what leaves the account, and the
  // point of publishing B2 is that it is complete. What must not appear is his
  // RATE: Shervin's call on 24 Aug 2026. The tenancy convention ("one month's
  // rent, pro-rated") is not his rate and stays.
  const forbidden = [
    /commission[^|]*\|[^|]*\d\s*% \+ GST/i, /our model/i,
    /rate card/i, /CEA does not set/i, /how to defend/i,
    /BRAND TOKENS/i, /DESIGN SYSTEM/i, /BUILD PROMPT/i, /BUILD ORDER/i,
    /WHAT'S STILL OPEN/i, /DECK OUTLINES/i, /SPEAKER NOTES/i,
  ];
  for (const [file, body] of all()) {
    for (const re of forbidden) {
      assert.ok(!re.test(body), `${file} contains ${re} — the allowlist in build-guides.mjs has leaked`);
    }
  }
});

test('the commission rows are redacted but still present', has, () => {
  // Present, because a cost table missing its largest line is a worse failure
  // than publishing a rate. Redacted, because the rate is not public.
  const md = read('absd-tdsr-ssd');
  const rows = [...md.matchAll(/^\|\s*\*{0,2}Agent commission\*{0,2}\s*\|(.*)$/gm)];
  assert.ok(rows.length >= 2, `found ${rows.length} commission rows, expected the buyer and seller tables`);
  for (const [, cells] of rows) {
    assert.match(cells, /Negotiable, agreed in writing/, 'a commission row was not redacted');
    assert.doesNotMatch(cells, /\d\s*%/, 'a commission percentage survived redaction');
  }
});

test('every guide declares where it came from and what it links to', has, () => {
  for (const [file, body] of all()) {
    assert.match(body, /^title: /m, `${file} has no title`);
    assert.match(body, /^source: deck-build-pack-/m, `${file} does not name its source`);
    assert.match(body, /^toolHref: \//m, `${file} links to no tool — a guide with no ask is a dead end`);
    assert.match(body, /GENERATED by scripts\/build-guides\.mjs/, `${file} is missing its do-not-edit banner`);
  }
});

/* ── the rates ──────────────────────────────────────────────────────────── */

test("the guide's BSD ladder matches the calculators", has, () => {
  // Scoped to the BSD section: the property-tax table further down uses the
  // same "First / Next / Above" shape and would otherwise be swept in.
  const md = section(read('absd-tdsr-ssd'), "Buyer's Stamp Duty");
  const rows = [...md.matchAll(/^\|\s*(?:First|Next|Above)\s+\$([\d,]+)\s*\|\s*([\d.]+)%\s*\|/gm)];
  assert.ok(rows.length >= 6, `found ${rows.length} BSD bands in the guide, expected 6`);
  const guideRates = rows.map(m => Number(m[2]) / 100);
  const codeRates = BSD_RESIDENTIAL.map(b => b.rate);
  assert.deepEqual(guideRates, codeRates,
    'the BSD ladder in the guide and in lib/calc/constants.js disagree');
});

test("the guide's ABSD grid matches the calculators", has, () => {
  const md = read('absd-tdsr-ssd');
  const row = label => {
    const m = new RegExp(`^\\|\\s*${label}\\s*\\|(.+)\\|\\s*$`, 'm').exec(md);
    assert.ok(m, `no ABSD row for ${label}`);
    return m[1].split('|').map(c => c.trim()).filter(c => /%/.test(c)).map(pctIn);
  };
  const sc = row('Singapore Citizen');
  assert.deepEqual(sc, [ABSD.SC[1], ABSD.SC[2], ABSD.SC[3]], 'SC ABSD row disagrees with constants.js');
  const pr = row('Singapore PR');
  assert.deepEqual(pr, [ABSD.SPR[1], ABSD.SPR[2], ABSD.SPR[3]], 'SPR ABSD row disagrees with constants.js');
  assert.ok(row('Foreigner').every(r => r === ABSD.FOREIGNER), 'foreigner ABSD disagrees with constants.js');
});

test("the guide's LTV table matches the calculators", has, () => {
  const md = read('absd-tdsr-ssd');
  const grab = label => {
    const m = new RegExp(`^\\|\\s*${label}[^|]*\\|\\s*\\*{0,2}([\\d.]+)%`, 'm').exec(md);
    assert.ok(m, `no LTV row matching ${label}`);
    return Number(m[1]) / 100;
  };
  assert.equal(grab('None \\(bank or HDB\\)'), LTV[0].max, 'first-loan LTV disagrees');
  assert.equal(grab('One existing'), LTV[1].max, 'second-loan LTV disagrees');
  assert.equal(grab('Two or more'), LTV[2].max, 'third-loan LTV disagrees');
});

test("the guide's TDSR, MSR and mortgage duty match the calculators", has, () => {
  const md = read('absd-tdsr-ssd');
  assert.match(md, new RegExp(`\\*\\*TDSR ${asPct(TDSR_LIMIT)}%\\*\\*`), 'TDSR disagrees with constants.js');
  assert.match(md, new RegExp(`\\*\\*MSR ${asPct(MSR_LIMIT)}%\\*\\*`), 'MSR disagrees with constants.js');
  assert.match(md, new RegExp(`${asPct(MORTGAGE_DUTY.rate)}% of the loan amount, capped at \\$${MORTGAGE_DUTY.cap}`),
    'mortgage stamp duty disagrees with constants.js');
});

/* ── the stress rate ────────────────────────────────────────────────────────
 * This was pinned as a known conflict on 24 Aug: the pack said 4.0%, the
 * calculators said 4.2%. Shervin resolved it at 4.0% the same day and the pin
 * was deleted, which is what a self-cleaning pin is for. What replaces it is
 * an ordinary agreement check, like every other rate above. */

test("the guide's stress rate matches the calculators", has, () => {
  const md = read('absd-tdsr-ssd');
  // The pack writes it to one decimal ("4.0%"), so compare at that precision
  // rather than letting 0.04 * 100 render as a bare "4".
  assert.match(md, new RegExp(`\\*\\*Stress test ${(STRESS_TEST_RATE * 100).toFixed(1)}% p\\.a\\.\\*\\*`),
    'the stress rate in the guide and in lib/calc/constants.js disagree');
});
