/**
 * The four decks, as guide pages.
 *
 *   npm run build:guides
 *
 * The decks are generated by python-pptx from one verified research base. That
 * base is the reason this is a script and not four hand-written pages: the
 * moment a guide is retyped, it can drift from the deck Shervin presents from,
 * and a client who reads one and then sees the other has caught the site out.
 *
 * So the research base is the source, the deck script reads it, and this reads
 * the same file. One place to change a rate, three places it lands.
 *
 * WHAT IS PUBLISHED IS AN ALLOWLIST, NOT A FILTER. Parts C, D, E, F and G of
 * the pack are the commission rate card, the brand internals, the deck
 * outlines and the open-questions list. None of them belong on a public page,
 * and the way this script guarantees that is by naming the sections it DOES
 * publish rather than the ones it does not. A new part added to the pack later
 * is invisible here until someone deliberately adds it, which is the right
 * direction for that mistake to fail in.
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const SRC = path.join(ROOT, 'content', 'source', 'deck-build-pack-v3.md');
const OUT = path.join(ROOT, 'content', 'guides');

/* Section keys are the `## ` headings in the pack, matched on their leading
 * code (A1, B2 …) so a reworded heading does not silently drop a section. */
const GUIDES = [
  {
    slug: 'absd-tdsr-ssd',
    deck: 1,
    title: 'What it costs to buy, and what it costs to sell',
    blurb: 'Every duty, every rule and every table that decides what leaves your account — buying and selling, in one place.',
    tool: { href: '/plan', label: 'Run these numbers on a price' },
    sections: ['A1', 'A3', 'B1', 'B2', 'A2'],
  },
  {
    slug: 'new-launch-vs-resale',
    deck: 2,
    title: 'New launch or resale — the cash flow decision',
    blurb: 'Not which is better. Which cash-flow shape fits the next four years, and what each one asks of you and when.',
    tool: { href: '/plan', label: 'Test both against your own numbers' },
    sections: ['A4', 'B1'],
  },
  {
    slug: 'decoupling',
    deck: 3,
    title: 'Decoupling, 99-1, and owning two',
    blurb: 'What the structures actually are, what they cost, where the ABSD break-even sits, and what IRAS has done about the ones that went too far.',
    tool: { href: '/plan', label: 'Price the second purchase' },
    sections: ['A7', 'A8', 'A1'],
  },
  {
    slug: 'renting',
    deck: 4,
    title: 'Renting — what landlords earn and what tenants pay',
    blurb: 'The rules on who may rent out, the quotas and caps, and both cash tables: what a landlord carries and what a tenant hands over at signing.',
    tool: { href: '/tools', label: 'Work out the sums' },
    sections: ['A5', 'B3', 'B4', 'A2'],
  },
];

/** Split the pack into `## ` sections, keyed by their leading code. */
function sectionsOf(md) {
  const out = new Map();
  const parts = md.split(/\n(?=## )/);
  for (const p of parts) {
    const m = /^## ([A-G]\d+)\.\s*(.+)/.exec(p);
    if (!m) continue;
    // Everything up to the next `# PART` banner, so a section never swallows
    // the part that follows it.
    const body = p.split(/\n(?=# PART )/)[0].trimEnd();
    out.set(m[1], { code: m[1], heading: m[2].trim(), body });
  }
  return out;
}

/**
 * The commission rows come out of the public cost tables.
 *
 * Part C — the rate card — was never in the allowlist, but B1 and B2 embed the
 * same figures inside the buyer's and seller's cost tables, so excluding Part C
 * alone did not keep them off the page. Shervin's call on 24 Aug 2026: the rate
 * is not public.
 *
 * The ROW STAYS. Deleting it would make a "full cost table" understate what
 * leaves a seller's account by the largest single line in it, which is a worse
 * failure than publishing the rate. Only the figure is replaced, and what
 * replaces it is true: CEA does not set commission rates, and his are
 * negotiable and agreed in writing before he starts.
 *
 * ONLY HIS PERCENTAGE RATE IS REDACTED. The tenancy rows say "one month's rent
 * for a 24-month lease, pro-rated" — that is the market's convention rather
 * than his rate card, it is what a tenant is quoted by whoever they call, and
 * the cash-at-signing worked example underneath is built on it. Blanking those
 * would leave a total on the page that its own table no longer explains.
 */
function redactCommission(md) {
  return md.replace(/^\|(\s*\*{0,2}Agent commission\*{0,2}\s*)\|(.*)\|\s*$/gm, (row, label, rest) => {
    if (!/\d\s*%|our model/i.test(rest)) return row;      // a convention, not a rate card
    const cells = rest.split('|').length;
    return `|${label}|` + Array(cells).fill(' Negotiable, agreed in writing ').join('|') + '|';
  });
}

/** Demote every heading one level: the page supplies the h1. */
const demote = s => s.replace(/^(#{2,5}) /gm, (_, h) => '#'.repeat(Math.min(6, h.length + 1)) + ' ');

async function main() {
  let raw;
  try { raw = await fs.readFile(SRC, 'utf8'); }
  catch { console.error(`No ${path.relative(ROOT, SRC)}. Copy the build pack in first.`); process.exit(1); }

  const found = sectionsOf(raw);
  const version = /^# Sales Deck Build Pack — (v\d+)/m.exec(raw)?.[1] || 'unknown';
  await fs.mkdir(OUT, { recursive: true });

  let wrote = 0;
  const missing = [];
  for (const g of GUIDES) {
    const picked = g.sections.map(code => found.get(code)).filter(Boolean);
    for (const code of g.sections) if (!found.has(code)) missing.push(`${g.slug} wanted ${code}`);
    if (!picked.length) continue;

    const body = picked
      .map(s => `## ${s.heading}\n\n${redactCommission(demote(s.body.replace(/^## .*\n/, '')))}`)
      .join('\n\n---\n\n');
    const fm = [
      '---',
      `title: ${JSON.stringify(g.title)}`,
      `slug: ${g.slug}`,
      `deck: ${g.deck}`,
      `blurb: ${JSON.stringify(g.blurb)}`,
      `toolHref: ${g.tool.href}`,
      `toolLabel: ${JSON.stringify(g.tool.label)}`,
      `sections: ${g.sections.join(', ')}`,
      `source: deck-build-pack-${version}`,
      `generated: ${new Date().toISOString().slice(0, 10)}`,
      '---',
      '',
      '<!-- GENERATED by scripts/build-guides.mjs from content/source/deck-build-pack-v3.md.',
      '     Do not edit this file. Edit the build pack and re-run `npm run build:guides`,',
      '     so the guide, the deck and the calculators cannot drift apart. -->',
      '',
    ].join('\n');

    await fs.writeFile(path.join(OUT, `${g.slug}.md`), fm + body + '\n');
    wrote++;
    console.log(`  ${g.slug.padEnd(22)} ${picked.map(s => s.code).join(' + ')}`);
  }

  console.log(`content/guides — ${wrote} guides from build pack ${version}`);
  if (missing.length) { console.error('MISSING SECTIONS:\n  ' + missing.join('\n  ')); process.exit(1); }
}

main().catch(e => { console.error(`BUILD GUIDES FAILED: ${e.message}`); process.exit(1); });
